### ISSUE TITLE
Won't run once built and deployed 

### ISSUE THREAD

**Issue by mchabotgit** [mjl38/PB_sample_app_QRCodes#1]
It works great from the powerbuiler IDE but once I deploy it the ,NET Assembly can't be accessed. I get unresolvable external nvo_qrencodedecode.

I've included all of the PB runtime files including those in the DotNet bin directory and the dll and pdb files and the relates zing files and updated the constructor event to point to the new dll location

Still powerbuilder can't create the nvo

Thoughts?

**Comment by mjl38** [comment]
Hi,
Sorry for the delay. I'm on a holiday. Is your executable 32 or 64 bit?

**Comment by mchabotgit** [comment]
Sorry I got it resolved... I had to move the dll files to the toot and change the relative path



 Thanks





Marc Chabot | Sr. It Specialist

ArcelorMittal Dofasco

IT Solutions | Box 2460, 1330 Burlington St. E.

Hamilton, Ontario L8N 3J5

T 905-548-7200 x6874 | F 905-548-7202



________________________________

**Comment by mjl38** [comment]
Great news!

**Comment by mchabotgit** [comment]
Thanks thus meets my needs...was using Google chart api but wanted a non internet option





Marc Chabot | Sr. It Specialist

ArcelorMittal Dofasco

IT Solutions | Box 2460, 1330 Burlington St. E.

Hamilton, Ontario L8N 3J5

T 905-548-7200 x6874 | F 905-548-7202



________________________________
